### ISSUE TITLE
upgrade frida -> needs upgrade rust

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2822]
when upgrading frida to 0.14
we get
```
error[E0658]: use of unstable library feature 'option_take_if'
   --> /Users/aviramhassan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/frida-gum-0.14.0/src/lib.rs:141:34
    |
141 |         let Some(it) = singleton.take_if(|it| Arc::strong_count(it) == 1) else {
    |                                  ^^^^^^^
    |
    = note: see issue #98934 <https://github.com/rust-lang/rust/issues/98934> for more information
    = help: add `#![feature(option_take_if)]` to the crate attributes to enable
    = note: this compiler was built on 2024-04-14; consider upgrading it if it is out of date
```
so probably need to update rust to update.

**Comment by gurkerl83** [comment]
I’ve been experimenting with mirrord for a few days now, running it alongside frida-rust 0.14.0 respectively the frida-gum from this package without encountering any related issues. It’s worth mentioning that frida is located relative to the mirrord project in my setup, but using the crate directly should yield the same results.

**Comment by aviramha** [comment]
Thanks for the report. Keen to hear about your use case, as most people don't compile mirrord and also update its dependencies 🤣 
Any chance you updated your Rust? Since the new frida can't actually compile without updating..
